## DAOS server configuration file.
#
## Location of this configuration file is determined by first checking for the
## path specified through the -f option of the daos_server command line.
## Otherwise, /etc/daos_server.conf is used.
#
#
## Name associated with the DAOS system.
## Immutable after reformat.
#
#name: daos
#
#
## Formatted state defined as any of:
##   * ext4 filesystem on IPMMs
##   * IPMMs in unexpected configuration
##   * NVMe device contains a blobstore with uuid in label
#
#
## Automatic provisioning
#
## If set to "true" then when daos_server starts it will try to perform
## provision and start servers automatically.
## During provision, if anything fails or a device is found to be in a
## "formatted state" then administrator is alerted (with hints as to why and
## what to do next) and no formatting is performed (behaviour is also
## dependent on the "format" parameter setting).
## When provision has been cancelled, administrator has to manually intervene,
## perform remediation and subsequently call provision API manually.
#
## If set to "false", administrator is in full control and performs workflow
## manually through client API (burn-in/fw-update/provision).
#
## default: true
#auto: false
#
#
## Formatting flow control
#
## Defines resultant behaviour when device is found to be in a formatted state.
## If set to "safe" and a device is found to be in a "formatted state", then
## administrator is alerted (with hints as to why/what to do next) and no
## formatting is performed.
#
## If set to "continue" and device is found to be in a "formatted state",
## continue to use those devices without reformatting.
#
## If set to "force" then automatically reformat and continue regardless of
## whether device is found to be in a "formatted state".
## Note: this may result in devices being formatted on reboot
#
## default: safe
#format: continue
#
#
## Access points
#
## To operate, DAOS will need a quorum of access point nodes to be available.
## Immutable after reformat.
## Hosts can be specified with or without port, default port below
## assumed if not specified.
#
## default: hostname of this node at port 10000 for local testing
#access_points: ['hostname1:10001','hostname2:10001','hostname3:10001']
#access_points: [hostname1,hostname2,hostname3]
#
#
## Force default port
#
## Force different port number to bind daos_server to, this will also
## be used when connecting to access points if no port is specified.
#
## default: 10000
#port: 10001
#
#
## Path to CA certificate
#
## If not specified, DAOS will start in insecure way which means that
## anybody can administrate the DAOS installation and access data
#
#ca_cert: ./.daos/ca.crt
#
#
## Path to server certificate and key file
#
## Discarded if no CA certificate is passed.
#
## default: ./.daos/daos_server.{crt,key}
#cert: ./.daosa/daos_server.crt
#key: ./.daosa/daos_server.key
#
#
## Fault domain path
#
## Immutable after reformat.
#
## default: /hostname for a local configuration w/o fault domain
#fault_path: /vcdu0/rack1/hostname
#
#
## Fault domain callback
#
## Path to executable which will return fault domain string.
## Immutable after reformat.
#
#fault_cb: ./.daos/fd_callback
#
#
## Use specific OFI interfaces
#
## Specify either a single fabric interface that will be used by all
## spawned servers or a comma-seperated list of fabric interfaces to be
## assigned individually.
## By default, the DAOS server will auto-detect and use all fabric
## interfaces if any and fall back to socket on the first eth card
## otherwise.
#
#fabric_ifaces: [qib0,qib1]
#
#
## Use specific OFI provider
#
## Force a specific provider to be used by all the servers.
## The default provider depends on the interfaces that will be auto-detected:
## ofi+psm2 for Omni-Path, ofi+verbs;ofi_rxm for Infiniband/RoCE and finally
## ofi+socket for non-RDMA-capable Ethernet.
#
#provider: ofi+verbs;ofi_rxm
#
#
## Mountpoint directory
#
## If no pre-configured mountpoins are specified, DAOS will auto-detect
## NVDIMMs, configure them in interleave mode, format with ext4 and
## mount with the DAX extension. This option allows to specify a
## preferred path where the mountpoints will be created.
#
## default: /mnt/daos
#scm_mount_path: /mnt/daosa
#
#
## NVMe SSD whitelist
#
## Only use NVMe controllers with specific PCI addresses.
## Immutable after reformat, colons replaced by dots in PCI identifiers.
## By default, DAOS will use all the NVMe-capable SSDs that don't have active
## mount points.
#
#bdev_include: [pcie1000.0.0.0.1,pcie1000.0.0.0.2,pcie1000.0.0.0.3]
#
#
## NVMe SSD blacklist
#
## Only use NVMe controllers with specific PCI addresses. Overrides drives
## listed in nvme_include and forces auto-detection to skip those drives.
## Immutable after reformat, colons replaced by dots in PCI identifiers.
#
#bdev_exclude: [pcie1000.0.0.0.1]
#
#
## Use Hyperthreads
#
## When Hyperthreading is enabled and supported on the system, this parameter
## defines whether the DAOS service thread should only be bound to different
## physical cores (value 0) or hyperthreads (value 1).
#
## default: false
#hyperthreads: true
#
#
## When per-server definitions exist, auto-allocation of resources is not
## performed. Without per-server definitions, node resources will
## automatically be assigned to servers based on NUMA ratings, there will
## be a one-to-one relationship between servers and sockets.
#
#
## Use the given directory for creating unix domain sockets
#
## DAOS Agent and DAOS Server both use unix domain sockets for communication
## with other system components. This setting is the base location to place
## the sockets in.
#
## default: /var/run/daos_server
#socket_dir: ./.daos/daos_server
#
#servers:
#-
#  # Rank to be assigned as identifier for server.
#  # Immutable after reformat.
#  # Optional parameter, will be auto generated if not supplied.
#
#  rank: 0
#
#  # Logical CPU assignments as identified in /proc/cpuinfo
#  # e.g. [0-24] for CPU 0 to 24.
#  # Immutable after reformat.
#
#  cpus: [0-20]
#
#  # Use specific OFI interfaces.
#  # Specify the fabric network interface that will be used by this server.
#  # Optionally specify the fabric network interface port that will be used
#  # by this server but please only if you have a specific need, this will
#  # normally be chosen automatically.
#
#  fabric_iface: qib0
#  fabric_iface_port: 20000
#
#  # Force specific debug mask (D_LOG_MASK) at start up time.
#  # By default, just use the default debug mask used by DAOS.
#  # Mask specifies minimum level of message significance to pass to logger.
#
#  log_mask: WARN
#
#  # Force specific path for DAOS debug logs.
#
#  # default: /tmp/daos_server
#  log_file: /tmp/daos_server1.log
#
#  # Pass specific environment variables to the DAOS server
#  # Empty by default.
#
#  env_vars:
#      - ABT_MAX_NUM_XSTREAMS=100
#      - CRT_TIMEOUT=30
#
#  # Define a pre-configured mountpoint for storage class memory to be used
#  # by this server.
#  # Path should be unique to server instance (can use different subdirs).
#
#  scm_mount: /mnt/daos/1
#
#  # Backend block device type. Force a SPDK driver to be used by this server
#  # instance.
#  # Options are:
#  # - "nvme" for NVMe SSDs (preferred option)
#  # - "malloc" to emulate a NVMe SSD with memory
#  # - "file" to emulate a NVMe SSD with a regular file
#  # - "kdev" to use a kernel block device
#  # Immutable after reformat.
#
#  # default: nvme
#  bdev_class: nvme
#
#  # Backend block device configuration to be used by this server instance.
#  # Immutable after reformat.
#  # When bdev_class is set to nvme, bdev_list is the list of unique NVMe IDs
#  # that should be different across different server instance.
#  # Colons replaced by dots in PCI identifiers.
#  bdev_list: [pcie1000.0.0.0.1]
#-
#  # Rank to be assigned as identifier for server.
#  # Immutable after reformat.
#  # Optional parameter, will be auto generated if not supplied.
#
#  rank: 1
#
#  # Logical CPU assignments as identified in /proc/cpuinfo
#  # e.g. [0-24] for CPU 0 to 24.
#  # Immutable after reformat.
#
#  cpus: [21-40]
#
#  # Use specific OFI interfaces.
#  # Specify the fabric network interface that will be used by this server.
#  # Optionally specify the fabric network interface port that will be used
#  # by this server but please only if you have a specific need, this will
#  # normally be chosen automatically.
#
#  fabric_iface: qib0
#  fabric_iface_port: 20000
#
#  # Force specific debug mask (D_LOG_MASK) at start up time.
#  # By default, just use the default debug mask used by DAOS.
#  # Mask specifies minimum level of message significance to pass to logger.
#
#  log_mask: WARN
#
#  # Force specific path for DAOS debug logs.
#
#  # default: /tmp/daos_server
#  log_file: /tmp/daos_server2.log
#
#  # Pass specific environment variables to the DAOS server
#  # Empty by default.
#
#  env_vars:
#      - ABT_MAX_NUM_XSTREAMS=200
#      - CRT_TIMEOUT=100
#
#  # Define a pre-configured mountpoint for storage class memory to be used
#  # by this server.
#  # Path should be unique to server instance (can use different subdirs).
#
#  scm_mount: /mnt/daos/2
#
#  # Backend block device type. Force a SPDK driver to be used by this server
#  # instance.
#  # Options are:
#  # - "nvme" for NVMe SSDs (preferred option)
#  # - "malloc" to emulate a NVMe SSD with memory
#  # - "file" to emulate a NVMe SSD with a regular file
#  # - "kdev" to use a kernel block device
#  # Immutable after reformat.
#
#  # When bdev_class is set to malloc, bdev_number is the number of devices
#  # to allocate and bdev_size is the size in GB of each individual device.
#  bdev_class: malloc
#  bdev_number: 1
#  bdev_size: 4
#
#  # When bdev_class is set to file, bdev_list is the list of file paths that
#  # will be used to emulate NVMe SSDs. The size of each file is specified by
#  # bdev_size in GB unit.
#  bdev_class: file
#  bdev_list: [/tmp/daos-bdev1,/tmp/daos-bdev2]
#  bdev_size: 16
#
#  # When bdev_class is set to kdev, bdev_list is the list of unique kernel
#  # block devices that should be different across different server instance.
#  bdev_class: kdev
#  bdev_list: [/dev/sdc,/dev/sdd]
